[tool.poetry]
name = "automlcli"
version = "0.2.0"
description = ""
authors = ["altescy <altescy@fastmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
colt = "^0.6.1"
fs = "^2.4.12"
fs-s3fs = "^1.1.1"
numpy = "^1.20.1"
omegaconf = "^2.0.6"
pandas = "^1.2.2"
requests = "^2.25.1"
tqdm = "^4.57.0"
flatten-dict = "^0.3.0"
flaml = {version = "^0.2.5", optional = true}
tpot = {version = "^0.11.7", optional = true}
mlflow = {version = "^1.14.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
python-language-server = "^0.36.2"
pysen = {version = "^0.9.1", extras = ["lint"]}
ipython = "^7.20.0"

[tool.poetry.extras]
flaml=["flaml"]
tpot=["tpot"]
mlflow=["mlflow"]
all=["flaml", "tpot", "mlflow"]

[tool.poetry.scripts]
automl = "automlcli.__main__:run"

[tool.pysen]
version = "0.9"

[tool.pysen-cli]
settings_dir = "."

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 88
py_version = "py38"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]

[tool.pysen.lint.source]
  includes = ["."]
  excludes = [".venv/"]

[tool.black] # automatically generated by pysen
line-length = 88
target-version = ["py38"]

[tool.isort] # automatically generated by pysen
default_section = "THIRDPARTY"
ensure_newline_before_comments = true
force_grid_wrap = 0
force_single_line = false
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
