name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry install --extras=all
        make clean
    - name: Lint with pylint
      run: |
        make lint
    - name: Check types with mypy
      run: |
        make mypy
    - name: Test with pytest
      run: |
        make test
